
########################## 重试机制 ##########################
#在生产环境中，由于各种各样的原因，可能会使一次请求偶然失败。考虑某些业务的体验，不能通过有感知的操作来触发，这时候会用到重试机制了
#zuul可以配合Ribbon来做重试。此功能要慎重使用，有一些接口要保证幂等性。
zuul: 
  retryable: true #开启重试

ribbon:
  MaxAutoRetries: 1 #同一个服务重试的次数(除去首次)
  MaxAutoRetriesNextServer: 1  #切换相同服务数量